// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';
import {feishu} from '../models';

export function ChooseFeedbackExportPath():Promise<string>;

export function ChooseFeishuBridgeSkillFolder():Promise<string>;

export function ChooseFeishuBridgeSkillZip():Promise<string>;

export function ClearLogs():Promise<void>;

export function ClearRequests():Promise<void>;

export function DeleteFeishuBridgeSkill(arg1:string):Promise<void>;

export function ExportFeedbackBundle(arg1:main.FeedbackExportOptions):Promise<main.FeedbackExportResult>;

export function ForceQuitApp():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<service.Config>;

export function GetDetectionInfo():Promise<main.DetectionInfo>;

export function GetFeishuBridgeConfig():Promise<feishu.Config>;

export function GetFeishuBridgeMCPJSON():Promise<main.MCPJSONFile>;

export function GetFeishuBridgeSkills():Promise<Array<feishu.BridgeSkill>>;

export function GetFeishuBridgeStatus():Promise<feishu.Status>;

export function GetLogDetail(arg1:string):Promise<main.AppLog>;

export function GetLogSummaries():Promise<Array<main.AppLog>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetRequestDetail(arg1:string):Promise<main.RequestRecord>;

export function GetRequestSummaries():Promise<Array<main.RequestRecord>>;

export function GetStatus():Promise<main.ProxyStatus>;

export function GetTokenStats():Promise<main.TokenStats>;

export function HideWindow():Promise<void>;

export function ImportFeishuBridgeSkillPath(arg1:string):Promise<feishu.BridgeSkillImportResult>;

export function InstallFeishuCLI():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenPathInFileManager(arg1:string):Promise<void>;

export function RecordBootMilestone(arg1:string):Promise<void>;

export function RefreshFeishuBridgeStatus():Promise<feishu.Status>;

export function RefreshModels():Promise<Array<main.ModelInfo>>;

export function ReinstallFeishuSkills():Promise<void>;

export function ReloadFeishuBridgeSkills():Promise<void>;

export function RequestQuitShortcut():Promise<void>;

export function SaveFeishuBridgeMCPJSON(arg1:string):Promise<main.MCPJSONFile>;

export function SelectModel(arg1:string):Promise<main.ProxyStatus>;

export function SetFeishuBridgeSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartFeishuBridge():Promise<void>;

export function StartFeishuCLILogin():Promise<void>;

export function StartFeishuCLISetupNew():Promise<void>;

export function StartProxy():Promise<void>;

export function StopFeishuBridge():Promise<void>;

export function StopProxy():Promise<void>;

export function UpdateConfig(arg1:service.Config):Promise<void>;

export function UpdateFeishuBridgeConfig(arg1:feishu.Config):Promise<void>;
