// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function ClearRequests():Promise<void>;

export function ForceQuitApp():Promise<void>;

export function GetConfig():Promise<service.Config>;

export function GetDetectionInfo():Promise<main.DetectionInfo>;

export function GetLogs():Promise<Array<main.AppLog>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetRequests():Promise<Array<main.RequestRecord>>;

export function GetStatus():Promise<main.ProxyStatus>;

export function GetTokenStats():Promise<main.TokenStats>;

export function HideWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function QuitApp():Promise<void>;

export function RefreshModels():Promise<Array<main.ModelInfo>>;

export function RequestQuitShortcut():Promise<void>;

export function SelectModel(arg1:string):Promise<main.ProxyStatus>;

export function ShowWindow():Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UpdateConfig(arg1:service.Config):Promise<void>;
