// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckPromptPackUpdate() {
  return window['go']['main']['App']['CheckPromptPackUpdate']();
}

export function ChooseFeedbackExportPath() {
  return window['go']['main']['App']['ChooseFeedbackExportPath']();
}

export function ChooseFeishuAgentSkillFolder() {
  return window['go']['main']['App']['ChooseFeishuAgentSkillFolder']();
}

export function ChooseFeishuAgentSkillZip() {
  return window['go']['main']['App']['ChooseFeishuAgentSkillZip']();
}

export function CleanupFeishuAgentArtifacts(arg1) {
  return window['go']['main']['App']['CleanupFeishuAgentArtifacts'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearRequests() {
  return window['go']['main']['App']['ClearRequests']();
}

export function DeleteFeishuAgentSkill(arg1) {
  return window['go']['main']['App']['DeleteFeishuAgentSkill'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['App']['DownloadAndInstallUpdate']();
}

export function ExportFeedbackBundle(arg1) {
  return window['go']['main']['App']['ExportFeedbackBundle'](arg1);
}

export function ForceQuitApp() {
  return window['go']['main']['App']['ForceQuitApp']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetectionInfo() {
  return window['go']['main']['App']['GetDetectionInfo']();
}

export function GetFeishuAgentConfig() {
  return window['go']['main']['App']['GetFeishuAgentConfig']();
}

export function GetFeishuAgentMCPJSON() {
  return window['go']['main']['App']['GetFeishuAgentMCPJSON']();
}

export function GetFeishuAgentSkills() {
  return window['go']['main']['App']['GetFeishuAgentSkills']();
}

export function GetFeishuAgentStatus() {
  return window['go']['main']['App']['GetFeishuAgentStatus']();
}

export function GetLogDetail(arg1) {
  return window['go']['main']['App']['GetLogDetail'](arg1);
}

export function GetLogSummaries() {
  return window['go']['main']['App']['GetLogSummaries']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOnlineUpdateStatus() {
  return window['go']['main']['App']['GetOnlineUpdateStatus']();
}

export function GetRequestDetail(arg1) {
  return window['go']['main']['App']['GetRequestDetail'](arg1);
}

export function GetRequestSummaries() {
  return window['go']['main']['App']['GetRequestSummaries']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTokenStats() {
  return window['go']['main']['App']['GetTokenStats']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportFeishuAgentSkillPath(arg1) {
  return window['go']['main']['App']['ImportFeishuAgentSkillPath'](arg1);
}

export function InstallFeishuCLI() {
  return window['go']['main']['App']['InstallFeishuCLI']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenPathInFileManager(arg1) {
  return window['go']['main']['App']['OpenPathInFileManager'](arg1);
}

export function RecordBootMilestone(arg1) {
  return window['go']['main']['App']['RecordBootMilestone'](arg1);
}

export function RefreshFeishuAgentStatus() {
  return window['go']['main']['App']['RefreshFeishuAgentStatus']();
}

export function RefreshModels() {
  return window['go']['main']['App']['RefreshModels']();
}

export function ReinstallFeishuSkills() {
  return window['go']['main']['App']['ReinstallFeishuSkills']();
}

export function ReloadFeishuAgentSkills() {
  return window['go']['main']['App']['ReloadFeishuAgentSkills']();
}

export function RequestQuitShortcut() {
  return window['go']['main']['App']['RequestQuitShortcut']();
}

export function SaveFeishuAgentMCPJSON(arg1) {
  return window['go']['main']['App']['SaveFeishuAgentMCPJSON'](arg1);
}

export function SelectModel(arg1) {
  return window['go']['main']['App']['SelectModel'](arg1);
}

export function SetFeishuAgentSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetFeishuAgentSkillEnabled'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartFeishuAgent() {
  return window['go']['main']['App']['StartFeishuAgent']();
}

export function StartFeishuCLILogin() {
  return window['go']['main']['App']['StartFeishuCLILogin']();
}

export function StartFeishuCLISetupNew() {
  return window['go']['main']['App']['StartFeishuCLISetupNew']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopFeishuAgent() {
  return window['go']['main']['App']['StopFeishuAgent']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateFeishuAgentConfig(arg1) {
  return window['go']['main']['App']['UpdateFeishuAgentConfig'](arg1);
}
