// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {feishu} from '../models';
import {service} from '../models';

export function CheckForUpdates():Promise<main.OnlineUpdateStatus>;

export function CheckPromptPackUpdate():Promise<feishu.PromptPackStatus>;

export function ChooseFeedbackExportPath():Promise<string>;

export function ChooseFeishuAgentSkillFolder():Promise<string>;

export function ChooseFeishuAgentSkillZip():Promise<string>;

export function CleanupFeishuAgentArtifacts(arg1:main.FeishuAgentCleanupOptions):Promise<Array<string>>;

export function ClearLogs():Promise<void>;

export function ClearRequests():Promise<void>;

export function DeleteFeishuAgentSkill(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate():Promise<main.OnlineUpdateStatus>;

export function ExportFeedbackBundle(arg1:main.FeedbackExportOptions):Promise<main.FeedbackExportResult>;

export function ForceQuitApp():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<service.Config>;

export function GetDetectionInfo():Promise<main.DetectionInfo>;

export function GetFeishuAgentConfig():Promise<feishu.Config>;

export function GetFeishuAgentMCPJSON():Promise<main.MCPJSONFile>;

export function GetFeishuAgentSkills():Promise<Array<feishu.AgentSkill>>;

export function GetFeishuAgentStatus():Promise<feishu.Status>;

export function GetLogDetail(arg1:string):Promise<main.AppLog>;

export function GetLogSummaries():Promise<Array<main.AppLog>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetOnlineUpdateStatus():Promise<main.OnlineUpdateStatus>;

export function GetRequestDetail(arg1:string):Promise<main.RequestRecord>;

export function GetRequestSummaries():Promise<Array<main.RequestRecord>>;

export function GetStatus():Promise<main.ProxyStatus>;

export function GetTokenStats():Promise<main.TokenStats>;

export function HideWindow():Promise<void>;

export function ImportFeishuAgentSkillPath(arg1:string):Promise<feishu.AgentSkillImportResult>;

export function InstallFeishuCLI():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenPathInFileManager(arg1:string):Promise<void>;

export function RecordBootMilestone(arg1:string):Promise<void>;

export function RefreshFeishuAgentStatus():Promise<feishu.Status>;

export function RefreshModels():Promise<Array<main.ModelInfo>>;

export function ReinstallFeishuSkills():Promise<void>;

export function ReloadFeishuAgentSkills():Promise<void>;

export function RequestQuitShortcut():Promise<void>;

export function SaveFeishuAgentMCPJSON(arg1:string):Promise<main.MCPJSONFile>;

export function SelectModel(arg1:string):Promise<main.ProxyStatus>;

export function SetFeishuAgentSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartFeishuAgent():Promise<void>;

export function StartFeishuCLILogin():Promise<void>;

export function StartFeishuCLISetupNew():Promise<void>;

export function StartProxy():Promise<void>;

export function StopFeishuAgent():Promise<void>;

export function StopProxy():Promise<void>;

export function UpdateConfig(arg1:service.Config):Promise<void>;

export function UpdateFeishuAgentConfig(arg1:feishu.Config):Promise<void>;
